apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: directories.example.com
  namespace: default 
spec:
  group: example.com
  names:
    kind: Directory
    plural: directories 
    singular: directory
    shortNames:
      - directory
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec: 
              type: object
              properties:
                replicas:
                  type: integer
                  format: int32
              required: ["replicas"]