apiVersion: example.com/v1
kind: Directory # Identifier of the resource type.
metadata:
  name: test-dir # Name of the "Directory" custom resource instance, may be changed to your liking
  namespace: default # Namespace must exist and account in KUBECONFIG must have sufficient permissions
spec:
  replicas: 2 # Number of "Directory" pods created.